### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Suhas-ks** [vi3k6i5/flashtext#103]
Any possibility to dump the KeywordProcessor object??
Or are pickle or dill modules enough for the job?

Thanks!

**Comment by NThakur20** [comment]
Hi Suhas, 

You can do this in two ways possible - 

1. (Preferred Way) I would basically create a keyword dictionary and pickle it. In the future, if you want to use the same keyword processor, then you will just need to load the pickle object and create the keyword processor object. 
`>>> keyword_dict = {`
`>>>     "java": ["java_2e", "java programing"],`
`>>>     "product management": ["PM", "product manager"]`
`>>> }`

2. You can even pickle the KeywordProcessor Object by itself.
`>>> import pickle`
`>>> pickle.dump( keywordProcessor, open( "kp.pkl", "wb" ) )`

Thanks,

Regards,
Nandan
