### ISSUE TITLE
Greek Language

### ISSUE THREAD

**Issue by psalias2006** [vi3k6i5/flashtext#110]
Hi I think is 
not working as supposed to with Greek language

![flash](https://user-images.githubusercontent.com/20187553/81831456-0c9bae00-9546-11ea-9bae-99e268661970.PNG)

```
from flashtext import KeywordProcessor
keyword_processor = KeywordProcessor()

keyword_processor.add_keywords_from_list(['πο'])
keyword_processor.extract_keywords('πομολο')
```

**Comment by iwpnd** [comment]
Flashtext does not know the greek alphabet.

```python
from flashtext import KeywordProcessor
keyword_processor = KeywordProcessor()
keyword_processor.set_non_word_boundaries(set('πομολο')) # or the entire script if you want

print(keyword_processor.non_word_boundaries)
>> {'μ', 'π', 'ο', 'λ'}

keyword_processor.add_keywords_from_list(['πο'])
keyword_processor.extract_keywords('πο μολο')
>> πο
```

if you don't put the space between `πο` and `μολο` extract_keywords() will not yield a result because `μ` is not a word boundary. if you want to understand how flashtext works, [this](https://arxiv.org/abs/1711.00046) will get you started.

**Comment by psalias2006** [comment]
> Flashtext does not know the greek alphabet.
> 
> ```python
> from flashtext import KeywordProcessor
> keyword_processor = KeywordProcessor()
> keyword_processor.set_non_word_boundaries(set('πομολο')) # or the entire script if you want
> 
> print(keyword_processor.non_word_boundaries)
> >> {'μ', 'π', 'ο', 'λ'}
> 
> keyword_processor.add_keywords_from_list(['πο'])
> keyword_processor.extract_keywords('πο μολο')
> >> πο
> ```
> 
> if you don't put the space between `πο` and `μολο` extract_keywords() will not yield a result because `μ` is not a word boundary. if you want to understand how flashtext works, [this](https://arxiv.org/abs/1711.00046) will get you started.

Thanks for the help! I'll give it a try

**Comment by psalias2006** [comment]
Based on @iwpnd post I have this workaround for greek words

```python
import string
from flashtext import KeywordProcessor

greek_simple = 'ΑαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσςΤτΥυΦφΧχΨψΩω'
greek_accent = 'άέήίόύώΆΈΉΊΌΎΏ'
non_word_boundaries = set(string.digits + string.ascii_letters + greek_simple + greek_accent + '_')

keyword_processor = KeywordProcessor()
keyword_processor.set_non_word_boundaries(non_word_boundaries)
```

thanks again!
