### ISSUE TITLE
Keyword not found - multi-word keywords

### ISSUE THREAD

**Issue by nfrancioso** [vi3k6i5/flashtext#121]
A single word keyword is not being found when its part of a multi-word keyword that is also part of the keyword list. (not sure how to explain this or if it makes sense but please see example below) Thanks.

        keyword_processor = KeywordProcessor()
        keyword_processor.add_keywords_from_list(["Senior Management", "Program Management", "Management"])
        keywords_found = keyword_processor.extract_keywords('I am in a Senior Management as a program management specialist.')
        print(keywords_found) ## ['Program Management', 'Senior Management']

'Management' should be found in the text but it is not.

**Comment by lc-billyfung** [comment]
my understanding of the algo is that it returns longest match first

**Comment by laomagic** [comment]
kp = KeywordProcessor()

kp.add_keyword("手机")
kp.add_keyword("苹果手机")
kp.add_keyword("vivo")
text = "手机vivo"
words = kp.extract_keywords(text)
print(words)
# ['vivo']

**Comment by nfrancioso** [comment]
not a bug.

**Comment by nfrancioso** [comment]
not a bug. longest match first is returned
