### ISSUE TITLE
Feature request: get number of keywords registered

### ISSUE THREAD

**Issue by kootenpv** [vi3k6i5/flashtext#15]
Maybe `len(kp)` or `kp.size`.

**Comment by vi3k6i5** [comment]
Added `len(kp)` as a feature in develop branch. Added `test/test_kp_len.py` as well.

**Comment by vi3k6i5** [comment]
Added in flashtext-2.4 :)

**Comment by kootenpv** [comment]
Very nice, am using it :) I was immediately interested in how many terms I had actually inserted in my project.
