### ISSUE TITLE
Replace keyword not working properly

### ISSUE THREAD

**Issue by NThakur20** [vi3k6i5/flashtext#20]
'''from flashtext import KeywordProcessor
kp = KeywordProcessor()
kp.add_keyword('+', 'plus')
kp.replace_keywords('c++')'''

**Comment by vi3k6i5** [comment]
@NThakur20 : This is not a valid case because FalshText matches words with word boundaries.

If you do the same thing with regex, you will get the exact same output:
```
import re
regex_match = re.compile(r'(?<!\w){}(?!\w)'.format(re.escape('+')))
print(regex_match.sub('plus', 'c++'))
# output: c+plus
```

Ref Link : https://stackoverflow.com/questions/45813658/regex-not-replacing-word-starting-with-or-ending-with-like-net-or-c
