### ISSUE TITLE
How do you deal with multiple recurring pattern?

### ISSUE THREAD

**Issue by dpanshu** [vi3k6i5/flashtext#23]
I have a query to detect 'Hi+'. Now a regex would be able to detect 'Hi', 'Hii', 'Hiii' and so on. How can I do that in fasttext without having to write all the possibilities?

**Comment by vi3k6i5** [comment]
Regex already exists to do exactly that. Flashtext was not designed for
this, simply speaking Flash Text can't do that. Hence I would recommend you
use regex for that instead.

There are really good regex libraries in python, you can choose any one for
this. Hope this helps. :)
