### ISSUE TITLE
[Feature suggestion] has_keywords() to check if there is one of the keywords in the text

### ISSUE THREAD

**Issue by bact** [vi3k6i5/flashtext#33]
We can currently do if extract_keywords(...) (will get True if one or more instances found),
but it has to go through the entire text.

To reduce time consumption for this use case,
does it possible to just return True when the first instance was found?

Thank you.

**Comment by vi3k6i5** [comment]
Hi @bact :
FlashText is really fast when the number of terms are >= 1000. The idea with it is to extract keywords or replace them.

To return if a word is present in a sentence or not, is a feature that's already there in python/regex libraries. A use case like that only makes sense if we are checking very few word and for that Regex will be much better.

If you can explain the use case which makes more sense with FlashText then maybe I will be able to help better. Let me know...

**Comment by vi3k6i5** [comment]
Closing as not suitable feature for FlashText and the same feature is already there in Regex/ other string libraries.

**Comment by bact** [comment]
I see. Thanks a lot for explanation. I give me better understanding of FlashText.

**Comment by vi3k6i5** [comment]
Glad I could help :)
