### ISSUE TITLE
Include links to other projects?

### ISSUE THREAD

**Issue by thoppe** [vi3k6i5/flashtext#36]
`flashtext` is great, thank you for building, documenting, and writing a post about it! 

I've incorporated it into our [pipeline](https://github.com/NIHOPA/NLPre) and saw a 60x speedup with respect to the regex matching we were doing. If you'd like to link back to our project (as proof yours is being used in the wild), feel free, or I can submit a PR for that. If not, thanks again for the quick drop-in library!

**Comment by vi3k6i5** [comment]
Thanks Travis,

Awesome, please do send, or if it's too much effort just send the link, I
will include it :)

Would love to showcase the usage happening out there.

Cheers,
Vikash

**Comment by vi3k6i5** [comment]
Amazing. I will check out your library in details. Seems like something I
could use.. :)

**Comment by thoppe** [comment]
@vi3k6i5 thanks! We made it in house, like you, to solve some of the problems we had with our text. Our problem wasn't scale, but historical or corrupted data.

**Comment by vi3k6i5** [comment]
Closing as PR is there. Thanks 👍
