### ISSUE TITLE
Search on file

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [vi3k6i5/flashtext#38]
Hi Team,

How can we search a keyword on a large file using flashtext, In the documentation I could see only on some sentences but not on any file. If there is any such thing please do redirect me to that page.

Thanks in advance

-Vijay N

**Comment by vi3k6i5** [comment]
To search anything less than a 500 keywords on a large file I would recommend using regex. It will be simpler and faster.

If you have more than few 1000 keywords go for FlashText.

To do it with FlashText you can load your file line by line and use keyword extractor function.

**Comment by vi3k6i5** [comment]
@narsapuramvijaykumar Closing the thread for now, Feel free to re-open if you still have doubts. Thanks :)
