### ISSUE TITLE
Suggestion: compile your trie to a regexp...

### ISSUE THREAD

**Issue by pygy** [vi3k6i5/flashtext#39]
You may get the best of both worlds (good algorithm, native-speed matcher) by actually compiling your trie to a regexp as https://github.com/ZhukovAlexander/triegex does...

**Comment by vi3k6i5** [comment]
I will try it out. Thanks @pygy :)

**Comment by pygy** [comment]
Someone ran preliminary benchmarks in the mean time, it looks like the approach could bear fruit:

https://www.reddit.com/r/programming/comments/7j3433/regex_was_taking_5_days_to_run_so_i_built_a_tool/dr45l9v/

**Comment by vi3k6i5** [comment]
Thanks @pygy That's a really good discussion, Lot's of learnings.

I wasn't able to use 


```t = Triegex('foo', 'bar', 'baz')

t.to_regex()

t.add('c++')

'spam' in t

import re

re.findall(t.to_regex(), 'c++')```

I wasn't able to use it, Full stack trace is too long, you can have a look at it. Also there is some issue after installation, import was not working.

```
    639             if item[0][0] in _REPEATCODES:
    640                 raise source.error("multiple repeat",
--> 641                                    source.tell() - here + len(this))
    642             if sourcematch("?"):
    643                 subpattern[-1] = (MIN_REPEAT, (min, max, item))

error: multiple repeat at position 19```

**Comment by vi3k6i5** [comment]
@pygy Thanks for pointing out to Trie Regex.

I will look for a solution to the `c++/ .NET` problem. I will switch as soon as I find a solution.

```
compiled_re = trie_regex_from_words(['c++'])

print(compiled_re.findall('c++ is awesome'))

compiled_re = trie_regex_from_words(['.Net'])

print(compiled_re.findall('.NET is awesome'))

# output:
# []
# []
```

Please let me know if you find any solution. Thanks 👍  

Closing the thread for now. Feel free to re-open if you think it's still valid.

**Comment by pygy** [comment]
@vi3k6i5 you need to escape special characters before creating the RegExp...

But then there's the issue of word boundaries. You don't want `ban` to match `banana` and, at least in JS, the `/\bc\+\+\b/i` escape sequence will not match `foo c++ bar` because `\b` only matches i `\w( those scenarios n?=\W)` or `\W(?=\w)` that are not met by `"+ "`.
