### ISSUE TITLE
not finding all occurrences of keywords

### ISSUE THREAD

**Issue by axelmuller** [vi3k6i5/flashtext#5]
Thanks for open-sourcing flashtext. 

I discovered a minor issue. I'm looking for genes in biological texts. I noticed that the gene **ire1** is not recognized in the following passage:

> targets relative to targets of the IRE1/XBP1s and PERK arms of the UPR

Prior to utilizing your script I used regexes and I padded each search terms with \b hence I was able to pick up genes that occurred in form of geneA/geneB. 

Thanks again, 
Axel

**Comment by vi3k6i5** [comment]
@axelmuller I understand the bug. Basically the project defines word boundaries as 
`self._white_space_chars` = set(['.', '\t', '\n', '\a', ' ', ','])`

So only \n or \t or ' ' or ',' is considered in word boundaries currently.

I was expecting that when someone will try the library expecting a '|' or '!' to act as word boundary and it won't work.

Thanks for raising the issue. What I will do is change word boundaries to be any character that is not alphanumeric.

Do you have any reference for what all characters are considered in '\b'. I can maybe learn something from there. I googled but couldn't find much.

**Comment by vi3k6i5** [comment]
added fix for this in version 1.9. Please try out and let me know.

**Comment by axelmuller** [comment]
Hi, that is great, thank you. 
\b in regex is similar to \W meaning all non alphanumeric characters. If you need a complete(-ish) list:

`import re                                                                       
chars = []                                                                      
unicode_range = range(0, 0x007e)                                                
r = re.compile('\W')                                                            
                                                                                
for i in unicode_range:                                                         
    chars.append(chr(i))                                                        
                                                                                
non_alphanumerics =  list(filter(r.match, chars)) `

Thanks again.

**Comment by vi3k6i5** [comment]
@axelmuller I updated the code in version 2.0 to consider add '_' to the word characters. now the list is `[a-zA-Z0-9_]`. I will close the bug now. Can you please drop me a email (id is there on my github profile). I wanted to discuss a bit more on the data set you are running this algorithm on.

I was planning to write a blog post about usage of this algorithm in the field of medical science document parsing /patent parsing etc.

Thanks

**Comment by vi3k6i5** [comment]
@axelmuller I would really appreciate it if you can help me with this.

Thanks
Vikash
