### ISSUE TITLE
Trigger multiple entries by same keyword?

### ISSUE THREAD

**Issue by easonnie** [vi3k6i5/flashtext#56]
I was trying to use a key word dict like this:
```
from flashtext import KeywordProcessor
keyword_processor = KeywordProcessor()
keyword_dict = {
    "java": ["java_2e", "java programing"],
    "product management": ["PM", "java_2e", "product manager"]
}
```
I thought the keyword `"jave_2e"` would trigger both `"java"` and `"product management"`. 

However, the output for the following code is:
```
keyword_processor.extract_keywords('I am a programmer for a java_2e platform')
```
Output:
```
['product management']
```
Expected output:
```
['java', 'product management']
```

It seems to be confused. I was wondering what is the correct way to trigger multiple entries by the same keyword.

**Comment by rmNULL** [comment]
Here's a way to do it( although I doubt if the author will be happy with this).
`keyword_processor.add_keyword('java_2e', ['java', 'product management', 'big word'])`

Note: 
  'java_2e'  keywords will be nested in list(run and believe :).

**Comment by easonnie** [comment]
Thanks a lot!

**Comment by rmNULL** [comment]
Hi @leobeeson 
the comment is outdated. 
I haven't used this software since long,
the current way to do this looks like this on the [documentation](https://flashtext.readthedocs.io/en/latest/api.html#add-keywords-from-list)
```python
keyword_processor.add_keywords_from_list(["java", "python"]})
```

**Comment by leobeeson** [comment]
Thanks @rmNULL, though your answer still works, particularly for the use case in the original question of triggering multiple entries by a same keyword (i.e. one-to-many instance-to-entity mapping). 

I tried your sample code and still runs in flashtext 2.7, but I couldn't find the `add_keyword` with a `str, List[str]` signature (which allows for one-to-many instance-to-entity mapping) in the current documentation. 

If we try to do this using the example in the current documentation, flashtext only returns one of the entries ("clean_name") with the desired keyword "unclean name"). 

Once again, thanks!
