### ISSUE TITLE
Consecutive Replacements with Empty Non Word Boundaries

### ISSUE THREAD

**Issue by xokocodo** [vi3k6i5/flashtext#65]
I have a use case where I need to replace "words" that could exit without spaces in between. I used the set_non_word_boundaries to have them be empty, and it works for the most part. There is a corner case that fails though.

If you have the keyword repeated it will skip the second consecutive instance.

>>> from flashtext import KeywordProcessor
>>> replacer = KeywordProcessor(case_sensitive=True)
>>> replacer.set_non_word_boundaries(set())
>>> replacer.add_keyword('old', 'new')
True
>>> replacer.replace_keywords("old old old old")
'new new new new'
>>> replacer.replace_keywords("oldoldoldold")
'newoldnewold'

**Comment by vi3k6i5** [comment]
The tool is no good if there is no word boundary. All optimizations are designed around the word boundary. Maybe just use standard regex or search in python it will work better. :)
