### ISSUE TITLE
add_keyword() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by ebauch** [vi3k6i5/flashtext#7]
Hi All,

I love the library and have been playing a bit with it. I came across a few difficulties, but maybe it is just me using it wrong. Adding more than 2 keywords throws an error:

![image](https://user-images.githubusercontent.com/3758223/30524277-9c516ea6-9bbe-11e7-9269-acdc6aacda5a.png)

From the readme, it is not really obvious that you can't specify more than 2 keyword permutations per line. In my example, I have about 5 terms that all mean the same thing. 

Here is a minimal code to reproduce the error: 

```
keyword_processor = KeywordProcessor()
keyword_processor.add_keyword('NV center', 'NV centre', 'Nitrogen-Vacancy')
sampletext = 'NV center NV centre Nitrogen-Vacancy Nitrogen Vacancy N-V'
keyword_processor.extract_keywords(sampletext)
```

I made it work finally, by adding each keyword per line, 

```
keyword_processor.add_keyword('NV center')
keyword_processor.add_keyword('NV centre')
keyword_processor.add_keyword('Nitrogen-Vacancy')
```

but the way I understand your examples: Add keywords per line are keywords with different meaning (like Bay area and New York), while adding keywords in one line is more for similar meaning keywords (e.g. New York and Big Apple).

**Comment by vi3k6i5** [comment]
@ebauch sorry for the late reply.

The library supports a dictionary addition option for exactly this use case:
```
keyword_processor = KeywordProcessor()
keyword_dict = {
    'framework': ['framework', 'frame work'],
    'spring framework': ['java spring','java spring framework', 'spring framework']
}
keyword_processor.add_keywords_from_dict(keyword_dict)
keywords_extracted = keyword_processor.extract_keywords(sampletext)
```

**Comment by vi3k6i5** [comment]
I will add these examples to the README and the [Docs](http://flashtext.readthedocs.io/en/latest/)

**Comment by vi3k6i5** [comment]
Added in docs and README. Please have a look and let me know if it's self explanatory.

Thanks :)
