### ISSUE TITLE
Is it possible to do like match of words?

### ISSUE THREAD

**Issue by nh111** [vi3k6i5/flashtext#89]
Is it possible to do like match of words?

Case 1 : Starts with keyword
Case 2 : Ends with Keyword
Case 3 : Contains keyword

Thanks in Advance.

**Comment by NThakur20** [comment]
@nh111, 

I would suggest using Regex for these tasks, and partial matching cannot be done with Flashtext.

Kind Regards,
Nandan Thakur

**Comment by nh111** [comment]
Thanks for your reply

**Comment by jiangweiatgithub** [comment]
How about adding a feature like "keyword_processor.add_word_boundary('o')", sot that  micro and soft woud match microsoft?
